### ISSUE TITLE
无prefix_kvdata表中的kv_value字段内容格式样例

### ISSUE THREAD

**Issue by five3** [Garfielt/GarfieltBlog-webpy#2]
prefix_kvdata表
kv_name=setting的记录对应的kv_value字段的值。
无样例，

**Comment by Garfielt** [comment]
data目录下新增加了一个sqlite样库可做本地体验使用，本地环境确保web.py安装的前提下直接python index.py即可，现代码正在部分重构、该bug，本周末放出。
