### ISSUE TITLE
运行python install.py，无出错提示，是表明安装GarfieltBlog-webpy成功吗

### ISSUE THREAD

**Issue by luckypoem** [Garfielt/GarfieltBlog-webpy#3]
hi.

as3:~/GarfieltBlog-webpy# ls
apps              index.py    LICENSE.txt  sessions    template
data              install.py  models       setting.py
GarfieltBlog.jpg  libs        README.md    static
as3:~/GarfieltBlog-webpy# python index.py
0.0 (1): SELECT \* FROM Garfielt_kvdata WHERE kv_name='setting'
http://0.0.0.0:8080/
Traceback (most recent call last):
  File "index.py", line 115, in <module>
    app.run()
  File "/usr/local/lib/python2.7/site-packages/web/application.py", line 313, in run
    return wsgi.runwsgi(self.wsgifunc(*middleware))
  File "/usr/local/lib/python2.7/site-packages/web/wsgi.py", line 54, in runwsgi
    return httpserver.runsimple(func, validip(listget(sys.argv, 1, '')))
  File "/usr/local/lib/python2.7/site-packages/web/httpserver.py", line 157, in runsimple
    server.start()
  File "/usr/local/lib/python2.7/site-packages/web/wsgiserver/**init**.py", line 1753, in start
    raise socket.error(msg)
socket.error: No socket could be created
as3:~/GarfieltBlog-webpy# python install.py
as3:~/GarfieltBlog-webpy# ls
apps              index.py     libs         README.md   setting.pyc
data              install.py   LICENSE.txt  sessions    static
GarfieltBlog.jpg  install.pyc  models       setting.py  template
as3:~/GarfieltBlog-webpy# cd data
as3:~/GarfieltBlog-webpy/data# ls
cache  Garfielt.db
as3:~/GarfieltBlog-webpy/data#

我是新手，可否写个详细的安装教程？

**Comment by Garfielt** [comment]
确保web.py已安装，直接checkout运行index.py即可。

**Comment by luckypoem** [comment]
hi.
我已装好：http://as3.brite.biz:8080/，
有2个问题，
如何修改8080端口为其他端口？
在哪里登录后台？

**Comment by Garfielt** [comment]
修改端口：启动时加端口参数（python index.py 80）
后台登陆：setting.py里login_url设定的地址
