### ISSUE TITLE
这个需要怎么配置环境啊，我想用在我的vps上面

### ISSUE THREAD

**Issue by Riverszhou** [Garfielt/GarfieltBlog-webpy#4]
可不可以给我给简单的部署步骤，谢谢

**Comment by Garfielt** [comment]
抱歉，刚看到，部署的话Python环境下安装webpy或将该包放到该博客根目录下，python index.py即可运行。
web.py适合入门，但因为开发者、社区的原因不看好今后发展，但好处是设计思路比较清晰，后续往tornado、flask、bottle上转吧

**Comment by Riverszhou** [comment]
感谢你提的建议，我学习web.py正式因为其简单便于理解，对于我还是非常好的。而且GarfieltBlog-webpy作为一个简单的cms类型的bolg还是非常具有学习价值的
